//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.18
//
//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import "AWSAPI_9HLT8N48WD_WeGoLocoClient.h"
